### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by LincolnSand** [InsaneMiner/UniversalOsDevQuestionCheckList#1]
You use `your` instead of `you're` in two different places.

First place:
> so your not asking basic programming questions

It should be:
> so you're not asking basic programming questions

Another place:
> If your on linux and you installed a cross compiler

should be:
> If you're on linux and you installed a cross compiler

**Comment by InsaneMiner** [comment]
> You use `your` instead of `you're` in two different places.
> 
> First place:
> 
> > so your not asking basic programming questions
> 
> It should be:
> 
> > so you're not asking basic programming questions
> 
> Another place:
> 
> > If your on linux and you installed a cross compiler
> 
> should be:
> 
> > If you're on linux and you installed a cross compiler

thank you
